### PR TITLE
Add papercolor themes

### PR DESCRIPTION
**Pull request by NLKNguyen**
GNOME Terminal color schemes (light & dark) based on [PaperColor](https://github.com/NLKNguyen/papercolor-theme/)

### CODE REVIEW

**Comment by bhilburn** [comment]
@chriskempson - Any chance that you could pull this? It would make things much easier for users of both projects!

**Comment by MarcosMenegazzo** [comment]
@NLKNguyen and @chriskempson if you dont mind i added papercolor to PR #23

**Comment by NLKNguyen** [comment]
@MarcosMenegazzo  I don't mind at all :smiley: 

Even though the following information has nothing to do with the PR, I just want to let you know that I'm revisiting PaperColor to support terminal's color palette and to enable multiple themes on top of it. It's kinda like Base16 in a sense but not about code generation. It's a long shot, but if you're interested in Vim and terminal color schemes, then please check back on this progress once in a while
https://github.com/NLKNguyen/papercolor-theme/blob/master/ROADMAP.md

**Comment by chriskempson** [comment]
I can't pull this sorry as the themes are generated by a base16 builder. See https://github.com/chriskempson/base16 for more info about how this works.

**Comment by MarcosMenegazzo** [comment]
@NLKNguyen thank you for the information about papercolor. I will take a look as soon as possible.
@chriskempson sorry i did not know about Base 16, so if you could, please consider updating all subprojects (base16-gnome-terminal, base16-templates-source, etc) readme file with a little explanation or a link to the main Base 16 project, so people can get the big picture easier. If i understood correctly, all files in this repo are generated by a builder tool, and PR #23 must be closed too. Is that right?

**Comment by chriskempson** [comment]
@MarcosMenegazzo Sorry, I've added a note to the readme now.

**Comment by MarcosMenegazzo** [comment]
@chriskempson No problems, well done. Thank you

**Pull request closed without merging**
